#!/usr/bin/env bash
# Setup script for code signing
# This script helps you generate keys and configure signing for Focust

set -e

echo "🔐 Focust Code Signing Setup"
echo "=============================="
echo ""

# Determine key path
if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "win32" ]]; then
    DEFAULT_KEY_PATH="$HOME/.tauri/focust.key"
else
    DEFAULT_KEY_PATH="$HOME/.tauri/focust.key"
fi

echo "This script will help you:"
echo "1. Generate a signing key pair"
echo "2. Update tauri.conf.json with the public key"
echo "3. Create a .env file for local development"
echo ""

read -p "Continue? (y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Setup cancelled."
    exit 0
fi

# Step 1: Generate key
echo ""
echo "📝 Step 1: Generate Signing Key"
echo "--------------------------------"
echo "Default path: $DEFAULT_KEY_PATH"
read -p "Enter key path (press Enter for default): " KEY_PATH
KEY_PATH=${KEY_PATH:-$DEFAULT_KEY_PATH}

# Create directory if it doesn't exist
mkdir -p "$(dirname "$KEY_PATH")"

if [[ -f "$KEY_PATH" ]]; then
    echo "⚠️  Key already exists at: $KEY_PATH"
    read -p "Overwrite? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Using existing key."
    else
        echo "Generating new key..."
        cd src-tauri
        bunx tauri signer generate -w "$KEY_PATH"
        cd ..
    fi
else
    echo "Generating key..."
    cd src-tauri
    bunx tauri signer generate -w "$KEY_PATH"
    cd ..
fi

# Extract public key from the key file
echo ""
echo "🔑 Extracting public key..."

# The public key is embedded in the key file or we need to generate it
# For now, ask user to copy it from the output
echo ""
echo "⚠️  IMPORTANT: Copy the PUBLIC KEY from the output above"
echo ""
read -p "Paste the public key here: " PUBLIC_KEY

if [[ -z "$PUBLIC_KEY" ]]; then
    echo "❌ Error: Public key is required"
    exit 1
fi

# Step 2: Update tauri.conf.json
echo ""
echo "📝 Step 2: Update Configuration"
echo "--------------------------------"

TAURI_CONF="src-tauri/tauri.conf.json"

if [[ ! -f "$TAURI_CONF" ]]; then
    echo "❌ Error: tauri.conf.json not found"
    exit 1
fi

# Backup original
cp "$TAURI_CONF" "${TAURI_CONF}.backup"

# Update pubkey using jq if available, otherwise use sed
if command -v jq &> /dev/null; then
    jq ".plugins.updater.pubkey = \"$PUBLIC_KEY\"" "$TAURI_CONF" > "${TAURI_CONF}.tmp"
    mv "${TAURI_CONF}.tmp" "$TAURI_CONF"
    echo "✅ Updated tauri.conf.json (backup saved)"
else
    echo "⚠️  jq not found, please manually update tauri.conf.json"
    echo "   Add this to plugins.updater.pubkey:"
    echo "   \"$PUBLIC_KEY\""
fi

# Step 3: Create .env file
echo ""
echo "📝 Step 3: Create .env File"
echo "----------------------------"

if [[ -f ".env" ]]; then
    echo "⚠️  .env file already exists"
    read -p "Overwrite? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Skipping .env creation."
    else
        cat > .env << EOF
# Tauri Updater Configuration
# Auto-generated by setup-signing.sh

# Path to your private signing key
TAURI_SIGNING_PRIVATE_KEY=yout_key_content_here

# If your key is password-protected, uncomment and set:
# TAURI_SIGNING_PRIVATE_KEY_PASSWORD=your_password_here
EOF
        echo "✅ Created .env file"
    fi
else
    cat > .env << EOF
# Tauri Updater Configuration
# Auto-generated by setup-signing.sh

# Path to your private signing key
TAURI_SIGNING_PRIVATE_KEY=your_key_content_here

# If your key is password-protected, uncomment and set:
# TAURI_SIGNING_PRIVATE_KEY_PASSWORD=your_password_here
EOF
    echo "✅ Created .env file"
fi

# Step 4: Instructions for GitHub
echo ""
echo "📝 Step 4: GitHub Secrets (for CI/CD)"
echo "--------------------------------------"
echo ""
echo "To enable signing in GitHub Actions, add these secrets:"
echo ""
echo "1. Go to: https://github.com/YOUR_USERNAME/Focust/settings/secrets/actions"
echo "2. Add new secret:"
echo "   Name: TAURI_SIGNING_PRIVATE_KEY"
echo "   Value: (content of $KEY_PATH)"
echo ""
echo "To get the key content:"
echo "   cat $KEY_PATH"
echo ""
if [[ -n "$KEY_PASSWORD" ]]; then
    echo "3. Add password secret (if applicable):"
    echo "   Name: TAURI_SIGNING_PRIVATE_KEY_PASSWORD"
    echo "   Value: your_key_password"
    echo ""
fi

echo "📚 For detailed instructions, see: docs/CODE_SIGNING.md"
echo ""
echo "✅ Setup complete!"
echo ""
echo "Next steps:"
echo "1. Commit tauri.conf.json (DO NOT commit .env or the private key)"
echo "2. Add secrets to GitHub (see above)"
echo "3. Test local build: just build"
echo ""
