#!/usr/bin/env bun

/**
 * Setup script for Tauri updater code signing
 *
 * This script helps you:
 *   1. Generate signing key pair
 *   2. Update `tauri.conf.json` with public key
 *   3. Create `.env` file for local development
 *   4. Provides GitHub Secrets setup instructions
 */

import * as os from "node:os";
import * as path from "node:path";
import { PATHS, SIGNING_KEY_DIR, SIGNING_KEY_EXTENSION } from "./lib/constants";
import {
  confirm,
  exec,
  exitWithError,
  file,
  getErrorMessage,
  getProjectName,
  logger,
  projectPath,
  prompt,
} from "./lib/utils";

// ============================================================================
// Key Management
// ============================================================================

function getDefaultKeyPath(): string {
  const projectName = getProjectName();
  return path.join(
    os.homedir(),
    SIGNING_KEY_DIR,
    `${projectName}${SIGNING_KEY_EXTENSION}`,
  );
}

function generateKey(keyPath: string): void {
  const keyDir = path.dirname(keyPath);
  if (!file.exists(keyDir)) {
    file.mkdir(keyDir);
  }

  if (file.exists(keyPath)) {
    logger.warning(`Key already exists: ${keyPath}`);
    if (!confirm("Overwrite?")) {
      logger.info("Using existing key");
      return;
    }
  }

  logger.info("Generating signing key...");
  const originalDir = projectPath();
  process.chdir(PATHS.TAURI_DIR);
  exec("bunx", ["tauri", "signer", "generate", "-w", keyPath]);
  process.chdir(originalDir);
  logger.success("Key generated successfully");
}

// ============================================================================
// Configuration Management
// ============================================================================

function updateTauriConfig(publicKey: string): void {
  const tauriConfPath = projectPath(PATHS.TAURI_CONFIG);

  if (!file.exists(tauriConfPath)) {
    exitWithError(`${PATHS.TAURI_CONFIG} not found`);
  }

  // Backup original
  file.copy(tauriConfPath, `${tauriConfPath}.backup`);

  // Update public key
  const config = JSON.parse(file.read(tauriConfPath));
  if (!config.plugins) {
    config.plugins = {};
  }
  if (!config.plugins.updater) {
    config.plugins.updater = {};
  }
  config.plugins.updater.pubkey = publicKey.trim();

  file.write(tauriConfPath, JSON.stringify(config, null, 2));
  logger.success(`Updated ${PATHS.TAURI_CONFIG} (backup saved)`);
}

function createEnvFile(): void {
  const envPath = projectPath(PATHS.ENV);
  const envContent = `# Tauri Updater Configuration
# Auto-generated by setup-updater-signing.ts

# Path to your private signing key
TAURI_SIGNING_PRIVATE_KEY=your_key_content_here

# If your key is password-protected, uncomment and set:
# TAURI_SIGNING_PRIVATE_KEY_PASSWORD=your_password_here
`;

  if (file.exists(envPath)) {
    logger.warning(`${PATHS.ENV} file already exists`);
    if (!confirm("Overwrite?")) {
      logger.info("Skipping .env creation");
      return;
    }
  }

  file.write(envPath, envContent);
  logger.success(`Created ${PATHS.ENV} file`);
}

// ============================================================================
// Main Logic
// ============================================================================

async function main(): Promise<void> {
  try {
    const projectName = getProjectName();
    logger.banner(`🔐 Code Signing Setup - ${projectName}`);
    logger.spacer();

    logger.multiline([
      "This script will help you:",
      "  1. Generate a signing key pair",
      `  2. Update ${PATHS.TAURI_CONFIG} with the public key`,
      `  3. Create a ${PATHS.ENV} file for local development`,
      "  4. Provide GitHub Secrets setup instructions",
    ]);
    logger.spacer();

    if (!confirm("Continue?")) {
      logger.info("Setup cancelled");
      process.exit(0);
    }

    logger.spacer();

    // Step 1: Generate key
    logger.step(1, "Generate Signing Key");
    const defaultKeyPath = getDefaultKeyPath();
    logger.info(`Default path: ${defaultKeyPath}`);
    const keyPathInput = prompt(
      "Enter key path (or press Enter for default): ",
    );
    const keyPath = keyPathInput.trim() || defaultKeyPath;
    logger.spacer();

    generateKey(keyPath);
    logger.spacer();

    // Extract public key
    logger.info("🔑 Please copy the PUBLIC KEY from the output above");
    logger.spacer();
    const publicKey = prompt("Paste the public key here: ");

    if (!publicKey.trim()) {
      exitWithError("Public key is required");
    }

    logger.spacer();

    // Step 2: Update configuration
    logger.step(2, "Update Configuration");
    updateTauriConfig(publicKey);
    logger.spacer();

    // Step 3: Create .env file
    logger.step(3, "Create .env File");
    createEnvFile();
    logger.spacer();

    // Step 4: GitHub instructions
    logger.step(4, "GitHub Secrets Setup");
    const keyReadCmd =
      os.platform() === "win32"
        ? `Get-Content '${keyPath}' -Raw`
        : `cat ${keyPath}`;

    logger.multiline([
      "To enable signing in GitHub Actions:",
      "",
      "1. Go to: https://github.com/YOUR_USERNAME/YOUR_REPO/settings/secrets/actions",
      "",
      "2. Add secret:",
      "   Name:  TAURI_SIGNING_PRIVATE_KEY",
      `   Value: (content of ${keyPath})`,
      "",
      "   To get the key content:",
      `   ${keyReadCmd}`,
      "",
      "3. If password-protected, add:",
      "   Name:  TAURI_SIGNING_PRIVATE_KEY_PASSWORD",
      "   Value: your_password",
      "",
      "📚 See docs/UPDATER_SIGNING.md for details",
    ]);
    logger.spacer();

    // Success
    logger.success("Setup complete! 🎉");
    logger.spacer();
    logger.multiline([
      "Next steps:",
      `  1. Commit ${PATHS.TAURI_CONFIG} (DO NOT commit ${PATHS.ENV} or private key)`,
      "  2. Add secrets to GitHub (see above)",
      "  3. Test local build: just build",
    ]);
  } catch (error) {
    logger.spacer();
    exitWithError(`Setup failed: ${getErrorMessage(error)}`);
  }
}

// ============================================================================
// Entry Point
// ============================================================================

main();
