# Setup script for code signing (Windows PowerShell)
# This script helps you generate keys and configure signing for Focust

Write-Host "🔐 Focust Code Signing Setup" -ForegroundColor Cyan
Write-Host "==============================" -ForegroundColor Cyan
Write-Host ""

# Determine key path
$defaultKeyPath = Join-Path $env:USERPROFILE ".tauri\focust.key"

Write-Host "This script will help you:"
Write-Host "1. Generate a signing key pair"
Write-Host "2. Update tauri.conf.json with the public key"
Write-Host "3. Create a .env file for local development"
Write-Host ""

$continue = Read-Host "Continue? (y/n)"
if ($continue -ne "y" -and $continue -ne "Y") {
    Write-Host "Setup cancelled."
    exit 0
}

# Step 1: Generate key
Write-Host ""
Write-Host "📝 Step 1: Generate Signing Key" -ForegroundColor Yellow
Write-Host "--------------------------------"
Write-Host "Default path: $defaultKeyPath"
$keyPath = Read-Host "Enter key path (press Enter for default)"
if ([string]::IsNullOrWhiteSpace($keyPath)) {
    $keyPath = $defaultKeyPath
}

# Create directory if it doesn't exist
$keyDir = Split-Path -Parent $keyPath
if (!(Test-Path $keyDir)) {
    New-Item -ItemType Directory -Force -Path $keyDir | Out-Null
}

if (Test-Path $keyPath) {
    Write-Host "⚠️  Key already exists at: $keyPath" -ForegroundColor Yellow
    $overwrite = Read-Host "Overwrite? (y/n)"
    if ($overwrite -eq "y" -or $overwrite -eq "Y") {
        Write-Host "Generating new key..."
        Push-Location src-tauri
        bunx tauri signer generate -w $keyPath
        Pop-Location
    } else {
        Write-Host "Using existing key."
    }
} else {
    Write-Host "Generating key..."
    Push-Location src-tauri
    bunx tauri signer generate -w $keyPath
    Pop-Location
}

# Extract public key
Write-Host ""
Write-Host "🔑 Extracting public key..." -ForegroundColor Yellow
Write-Host ""
Write-Host "⚠️  IMPORTANT: Copy the PUBLIC KEY from the output above" -ForegroundColor Yellow
Write-Host ""
$publicKey = Read-Host "Paste the public key here"

if ([string]::IsNullOrWhiteSpace($publicKey)) {
    Write-Host "❌ Error: Public key is required" -ForegroundColor Red
    exit 1
}

# Step 2: Update tauri.conf.json
Write-Host ""
Write-Host "📝 Step 2: Update Configuration" -ForegroundColor Yellow
Write-Host "--------------------------------"

$tauriConf = "src-tauri\tauri.conf.json"

if (!(Test-Path $tauriConf)) {
    Write-Host "❌ Error: tauri.conf.json not found" -ForegroundColor Red
    exit 1
}

# Backup original
Copy-Item $tauriConf "$tauriConf.backup"

# Update pubkey
$config = Get-Content $tauriConf -Raw | ConvertFrom-Json
if (!$config.plugins) {
    $config | Add-Member -MemberType NoteProperty -Name "plugins" -Value @{}
}
if (!$config.plugins.updater) {
    $config.plugins | Add-Member -MemberType NoteProperty -Name "updater" -Value @{}
}
$config.plugins.updater.pubkey = $publicKey

$config | ConvertTo-Json -Depth 10 | Set-Content $tauriConf

Write-Host "✅ Updated tauri.conf.json (backup saved)" -ForegroundColor Green

# Step 3: Create .env file
Write-Host ""
Write-Host "📝 Step 3: Create .env File" -ForegroundColor Yellow
Write-Host "----------------------------"

$envContent = @"
# Tauri Updater Configuration
# Auto-generated by setup-signing.ps1

# Path to your private signing key
TAURI_SIGNING_PRIVATE_KEY=your_key_content_here

# If your key is password-protected, uncomment and set:
# TAURI_SIGNING_PRIVATE_KEY_PASSWORD=your_password_here
"@

if (Test-Path ".env") {
    Write-Host "⚠️  .env file already exists" -ForegroundColor Yellow
    $overwrite = Read-Host "Overwrite? (y/n)"
    if ($overwrite -eq "y" -or $overwrite -eq "Y") {
        $envContent | Set-Content ".env"
        Write-Host "✅ Created .env file" -ForegroundColor Green
    } else {
        Write-Host "Skipping .env creation."
    }
} else {
    $envContent | Set-Content ".env"
    Write-Host "✅ Created .env file" -ForegroundColor Green
}

# Step 4: Instructions for GitHub
Write-Host ""
Write-Host "📝 Step 4: GitHub Secrets (for CI/CD)" -ForegroundColor Yellow
Write-Host "--------------------------------------"
Write-Host ""
Write-Host "To enable signing in GitHub Actions, add these secrets:"
Write-Host ""
Write-Host "1. Go to: https://github.com/YOUR_USERNAME/Focust/settings/secrets/actions"
Write-Host "2. Add new secret:"
Write-Host "   Name: TAURI_SIGNING_PRIVATE_KEY"
Write-Host "   Value: (content of $keyPath)"
Write-Host ""
Write-Host "To get the key content:"
Write-Host "   Get-Content '$keyPath' -Raw"
Write-Host ""
Write-Host "3. If your key is password-protected, add:"
Write-Host "   Name: TAURI_SIGNING_PRIVATE_KEY_PASSWORD"
Write-Host "   Value: your_key_password"
Write-Host ""

Write-Host "📚 For detailed instructions, see: docs\CODE_SIGNING.md"
Write-Host ""
Write-Host "✅ Setup complete!" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:"
Write-Host "1. Commit tauri.conf.json (DO NOT commit .env or the private key)"
Write-Host "2. Add secrets to GitHub (see above)"
Write-Host "3. Test local build: just build"
Write-Host ""
